spring:
  datasource :
    url: jdbc:h2:mem:dev-db
    username : dev
    password : pass
    driverClassName : org.h2.Driver
  jpa:
    database-platform : org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  security:
    user:
      name: dev
      password : pass
#logging:
#  level:
#    org.springframework.security : trace